# LinkedIn Profiles Gallery - Railway Platform Configuration
# Version: 1.0.0

[build]
builder = "nixpacks"
buildCommand = "npm run build"
watchPatterns = [
  "src/**/*",
  "prisma/**/*"
]

[deploy]
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/api/health"
interval = "30s"
timeout = "10s"
retries = 3

[services.web]
resources.cpu = 1
resources.memory = "512MB"
resources.instances.min = 1
resources.instances.max = 10
port = 3000
command = "npm start"
envVars = [
  "NODE_ENV=production",
  "PORT=3000"
]

[services.database]
type = "postgresql"
version = "14"
resources.cpu = 2
resources.memory = "1GB"
resources.storage = "100GB"

[services.database.configuration]
maxConnections = 100
sslMode = "require"
timezone = "UTC"

[services.cache]
type = "redis"
version = "6"
resources.memory = "256MB"
resources.maxmemory-policy = "allkeys-lru"

[services.cache.configuration]
maxmemory = "256mb"
maxmemory-samples = 5
appendonly = "yes"

[plugins.cdn]
enabled = true

[plugins.cdn.cacheControl]
default = "public, max-age=3600"
static = "public, max-age=31536000"

[plugins.monitoring]
enabled = true
metrics = [
  "cpu",
  "memory",
  "requests",
  "errors"
]

[plugins.monitoring.alerting]
errorRate = ">1%"
responseTime = ">200ms"

[project]
name = "linkedin-profiles-gallery"
environment = "production"